# Generated by Django 5.0.1 on 2024-07-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_hall_schedules_m_hall_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='level_id',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='semester_id',
        ),
    ]
