# Generated by Django 5.0.1 on 2024-07-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hall',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
